/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace PaymentRequest {
  export type PaymentRequestDataStruct = {
    merchant: AddressLike;
    tokenSymbol: string;
    chainId: BigNumberish;
    amount: BigNumberish;
    timestamp: BigNumberish;
    status: BigNumberish;
    payer: AddressLike;
    paidAt: BigNumberish;
  };

  export type PaymentRequestDataStructOutput = [
    merchant: string,
    tokenSymbol: string,
    chainId: bigint,
    amount: bigint,
    timestamp: bigint,
    status: bigint,
    payer: string,
    paidAt: bigint
  ] & {
    merchant: string;
    tokenSymbol: string;
    chainId: bigint;
    amount: bigint;
    timestamp: bigint;
    status: bigint;
    payer: string;
    paidAt: bigint;
  };
}

export interface PaymentRequestInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addSupportedChain"
      | "addSupportedToken"
      | "cancelPaymentRequest"
      | "createPaymentRequest"
      | "getCurrentPaymentId"
      | "getPaymentRequest"
      | "isChainSupported"
      | "isTokenSupported"
      | "markAsPaid"
      | "nextPaymentId"
      | "owner"
      | "paymentExists"
      | "paymentRequests"
      | "removeSupportedChain"
      | "removeSupportedToken"
      | "renounceOwnership"
      | "supportedChains"
      | "supportedTokens"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "PaymentCancelled"
      | "PaymentFulfilled"
      | "PaymentRequestCreated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addSupportedChain",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "addSupportedToken",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelPaymentRequest",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createPaymentRequest",
    values: [AddressLike, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentPaymentId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPaymentRequest",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isChainSupported",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isTokenSupported",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "markAsPaid",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "nextPaymentId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "paymentExists",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "paymentRequests",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "removeSupportedChain",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "removeSupportedToken",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "supportedChains",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supportedTokens",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "addSupportedChain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addSupportedToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelPaymentRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createPaymentRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentPaymentId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPaymentRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isChainSupported",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isTokenSupported",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "markAsPaid", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextPaymentId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "paymentExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "paymentRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeSupportedChain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeSupportedToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportedChains",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportedTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentCancelledEvent {
  export type InputTuple = [paymentId: BigNumberish, cancelledAt: BigNumberish];
  export type OutputTuple = [paymentId: bigint, cancelledAt: bigint];
  export interface OutputObject {
    paymentId: bigint;
    cancelledAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentFulfilledEvent {
  export type InputTuple = [
    paymentId: BigNumberish,
    payer: AddressLike,
    paidAt: BigNumberish
  ];
  export type OutputTuple = [paymentId: bigint, payer: string, paidAt: bigint];
  export interface OutputObject {
    paymentId: bigint;
    payer: string;
    paidAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentRequestCreatedEvent {
  export type InputTuple = [
    paymentId: BigNumberish,
    merchant: AddressLike,
    tokenSymbol: string,
    chainId: BigNumberish,
    amount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    paymentId: bigint,
    merchant: string,
    tokenSymbol: string,
    chainId: bigint,
    amount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    paymentId: bigint;
    merchant: string;
    tokenSymbol: string;
    chainId: bigint;
    amount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PaymentRequest extends BaseContract {
  connect(runner?: ContractRunner | null): PaymentRequest;
  waitForDeployment(): Promise<this>;

  interface: PaymentRequestInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addSupportedChain: TypedContractMethod<
    [chainId: BigNumberish],
    [void],
    "nonpayable"
  >;

  addSupportedToken: TypedContractMethod<
    [tokenSymbol: string],
    [void],
    "nonpayable"
  >;

  cancelPaymentRequest: TypedContractMethod<
    [paymentId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createPaymentRequest: TypedContractMethod<
    [
      merchant: AddressLike,
      tokenSymbol: string,
      chainId: BigNumberish,
      amount: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  getCurrentPaymentId: TypedContractMethod<[], [bigint], "view">;

  getPaymentRequest: TypedContractMethod<
    [paymentId: BigNumberish],
    [PaymentRequest.PaymentRequestDataStructOutput],
    "view"
  >;

  isChainSupported: TypedContractMethod<
    [chainId: BigNumberish],
    [boolean],
    "view"
  >;

  isTokenSupported: TypedContractMethod<
    [tokenSymbol: string],
    [boolean],
    "view"
  >;

  markAsPaid: TypedContractMethod<
    [paymentId: BigNumberish, payer: AddressLike],
    [void],
    "nonpayable"
  >;

  nextPaymentId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  paymentExists: TypedContractMethod<
    [paymentId: BigNumberish],
    [boolean],
    "view"
  >;

  paymentRequests: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, bigint, string, bigint] & {
        merchant: string;
        tokenSymbol: string;
        chainId: bigint;
        amount: bigint;
        timestamp: bigint;
        status: bigint;
        payer: string;
        paidAt: bigint;
      }
    ],
    "view"
  >;

  removeSupportedChain: TypedContractMethod<
    [chainId: BigNumberish],
    [void],
    "nonpayable"
  >;

  removeSupportedToken: TypedContractMethod<
    [tokenSymbol: string],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  supportedChains: TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;

  supportedTokens: TypedContractMethod<[arg0: string], [boolean], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addSupportedChain"
  ): TypedContractMethod<[chainId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "addSupportedToken"
  ): TypedContractMethod<[tokenSymbol: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "cancelPaymentRequest"
  ): TypedContractMethod<[paymentId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createPaymentRequest"
  ): TypedContractMethod<
    [
      merchant: AddressLike,
      tokenSymbol: string,
      chainId: BigNumberish,
      amount: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getCurrentPaymentId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPaymentRequest"
  ): TypedContractMethod<
    [paymentId: BigNumberish],
    [PaymentRequest.PaymentRequestDataStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "isChainSupported"
  ): TypedContractMethod<[chainId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "isTokenSupported"
  ): TypedContractMethod<[tokenSymbol: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "markAsPaid"
  ): TypedContractMethod<
    [paymentId: BigNumberish, payer: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "nextPaymentId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "paymentExists"
  ): TypedContractMethod<[paymentId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "paymentRequests"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, bigint, string, bigint] & {
        merchant: string;
        tokenSymbol: string;
        chainId: bigint;
        amount: bigint;
        timestamp: bigint;
        status: bigint;
        payer: string;
        paidAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "removeSupportedChain"
  ): TypedContractMethod<[chainId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeSupportedToken"
  ): TypedContractMethod<[tokenSymbol: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "supportedChains"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "supportedTokens"
  ): TypedContractMethod<[arg0: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PaymentCancelled"
  ): TypedContractEvent<
    PaymentCancelledEvent.InputTuple,
    PaymentCancelledEvent.OutputTuple,
    PaymentCancelledEvent.OutputObject
  >;
  getEvent(
    key: "PaymentFulfilled"
  ): TypedContractEvent<
    PaymentFulfilledEvent.InputTuple,
    PaymentFulfilledEvent.OutputTuple,
    PaymentFulfilledEvent.OutputObject
  >;
  getEvent(
    key: "PaymentRequestCreated"
  ): TypedContractEvent<
    PaymentRequestCreatedEvent.InputTuple,
    PaymentRequestCreatedEvent.OutputTuple,
    PaymentRequestCreatedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PaymentCancelled(uint256,uint256)": TypedContractEvent<
      PaymentCancelledEvent.InputTuple,
      PaymentCancelledEvent.OutputTuple,
      PaymentCancelledEvent.OutputObject
    >;
    PaymentCancelled: TypedContractEvent<
      PaymentCancelledEvent.InputTuple,
      PaymentCancelledEvent.OutputTuple,
      PaymentCancelledEvent.OutputObject
    >;

    "PaymentFulfilled(uint256,address,uint256)": TypedContractEvent<
      PaymentFulfilledEvent.InputTuple,
      PaymentFulfilledEvent.OutputTuple,
      PaymentFulfilledEvent.OutputObject
    >;
    PaymentFulfilled: TypedContractEvent<
      PaymentFulfilledEvent.InputTuple,
      PaymentFulfilledEvent.OutputTuple,
      PaymentFulfilledEvent.OutputObject
    >;

    "PaymentRequestCreated(uint256,address,string,uint256,uint256,uint256)": TypedContractEvent<
      PaymentRequestCreatedEvent.InputTuple,
      PaymentRequestCreatedEvent.OutputTuple,
      PaymentRequestCreatedEvent.OutputObject
    >;
    PaymentRequestCreated: TypedContractEvent<
      PaymentRequestCreatedEvent.InputTuple,
      PaymentRequestCreatedEvent.OutputTuple,
      PaymentRequestCreatedEvent.OutputObject
    >;
  };
}
